@startuml

interface ReviewService {
    +addReview(review: Review, userID: int, bookID: int): Review
    +getReviewsByUser(userID: int): List<Review>
    +getBookReviews(bookID: int): List<Review>
    +getReviews(): List<Review>
}

class Review {
    +id: int
    +rating: int
    +comment: String
}

ReviewService --> Review: Uses

@enduml